name: Build Check & PHPUnit

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
            - develop
            - ^feature/.+

jobs:
    php_unit:
        name: php unittest
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: ['7.4', '8.2', '8.3']
                wp-versions: ['6.8', '6.9', '7.0']
        services:
            mysql:
                image: mysql:5.7
                ports:
                    - 3306
                env:
                    MYSQL_ROOT_PASSWORD: wordpress
                    MYSQL_DATABASE: wordpress
                    MYSQL_USER: wordpress
                    MYSQL_PASSWORD: wordpress
        steps:
            - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
              with:
                  persist-credentials: false
            - name: Cache multiple paths
              uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
              with:
                  path: vendor
                  key: ${{ runner.os }}-php${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
            - name: Setup PHP ${{ matrix.php-versions }}
              uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
              with:
                  php-version: ${{ matrix.php-versions }}
            - name: Setup Node
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
              with:
                  node-version: 24.x
            - name: install npm scripts
              run: npm install
            - name: install Composer Package
              run: composer install
            - name: PHP CodeSniffer
              run: composer phpcs
            - name: Install WP-CLI
              run: |
                  curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
                  chmod +x wp-cli.phar
                  mv wp-cli.phar /usr/local/bin/wp
            - name: Install several WordPress version by wp-env.override.json
              run: WP_ENV_PHP_VERSION=${{ matrix.php-versions }} WP_ENV_CORE=WordPress/WordPress#${{ matrix.wp-versions }} npm run wp-env start --update
            - name: Check WordPress Version
              run: npm run wp-env run cli wp core version
            - name: PHP Unit Test
              run: npm run phpunit
